### ISSUE TITLE
Memory resets in the tests?

### ISSUE THREAD

**Issue by gdalle** [thorek1/MacroModelling.jl#34]
https://github.com/thorek1/MacroModelling.jl/blob/f4e752e931b490f01882e9ae8046d8c6b57eaff8/test/runtests.jl#L31

Why is this needed after every test set?

https://github.com/openjournals/joss-reviews/issues/5598

**Comment by thorek1** [comment]
indeed tests on the windows machine running 1.8 fail with out of memory error messages. the highlighted code was an attempt to overcome this issue be deleting the large model objects and triggering the garbage collector. my current best understanding is that the out of memory errors persist because the compiled functions are kept in memory. a lot of functions are compiled in case of higher order Taylor approximations of the model. in order to have the CI runs go through without errors, I can either drop the 1.8 windows run or avoid doing 3rd order for 1.8. windows. all other CI runs are unaffected

**Comment by gdalle** [comment]
Have you checked if the variable m actually contains anything after a test set? From what I can tell, the macro introduces a local scope anyway (https://docs.julialang.org/en/v1/stdlib/Test/#Working-with-Test-Sets) so my guess is m is not assigned

**Comment by gdalle** [comment]
Do you have any support for your intuition that memory runs out because of the size of the compiled code? That sounds very surprising to me

**Comment by thorek1** [comment]
I know that when i setup a model everything related to the model is kept in a struct with the name of the model. I also know that he compiles the functions and i guess they are kept in memory. i will go through the julia docs to find a way to give me a breakdown of the objects occupying memory inside a julia session...

**Comment by gdalle** [comment]
Honestly I don't have an issue with removing the tests on Windows, and I will tick the CI box in the review as long as it runs on Ubuntu. I just find it very puzzling and I'd like to fix it together instead of sweeping it under the rug ^^

**Comment by thorek1** [comment]
To be checked if this is related: 

https://discourse.julialang.org/t/the-improvement-of-memory-management-in-multihtreading-julia-1-10beta-is-amazing/102468

**Comment by gdalle** [comment]
okay then let's close
