### ISSUE TITLE
plot_irf gives unexpected results

### ISSUE THREAD

**Issue by duzaichuan** [thorek1/MacroModelling.jl#65]
```
@model BM begin
    c[0]^(-1) = α*β * c[1]^-1 * a[1] * k[0]^(α - 1.0)
    k[0] = a[0] * k[-1]^α - c[0]
    log(a[0]) = ρ * log(a[-1]) + σ_a * eps_a[x]
end

@parameters BM begin
    α = 0.3
    β = 0.96
    ρ = 0.5
    σ_a = 0.2
end

plot_irf(BM, periods=30)
get_irf(BM, periods=30)
```

I tested the above simple RBC model with the latest release on Julia 1.10 archlinux.

`get_irf` gives following expected results:
> [:, :, 1] ~ (:, :, :eps_a):
	(1)          (2)          …  (30)
  (:a)    0.2          0.1              3.72529e-10
  (:c)    0.0835259    0.0668207        3.88948e-10
  (:k)    0.0337857    0.0270286        1.57327e-10

However, the plot command shows different percent deviations.
[irf__BM__eps_a__1.pdf](https://github.com/thorek1/MacroModelling.jl/files/13812982/irf__BM__eps_a__1.pdf)

**Comment by thorek1** [comment]
`get_irf` returns absolute deviations by default. use `levels=true` to get absolute levels. percent deviations are not supported by keywords.

this wasn't clear from the doctoring: `?get_irf`. I fixed it (see upcoming release) so that it is now clear that the default values are absolute deviations from the relevant steady state

**Comment by duzaichuan** [comment]
Thanks, I got it.
